# Generated by Django 4.2 on 2023-04-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jsondata_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondata',
            old_name='data',
            new_name='file',
        ),
    ]
