# Generated by Django 4.2 on 2023-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_data_jsondata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='title',
            field=models.CharField(default='Post JSON Data', max_length=255),
        ),
    ]
